### ISSUE TITLE
"Deskband host for wbf" opens up instead of toolbar

### ISSUE THREAD

**Issue by Jimmyhogs** [AudioBand/AudioBand#106]
## Description
The Program was working fine whenever I installed it earlier. A few hour later, the bug randomly started after restarting my taskbar so many times, it was like a blank Spotify interface while the music was playing and only the play button was working (nothing else was showing up), so I uninstalled the program through the installer file, then reinstalled it, then when I went to open the toolbar, it started opening explorer saying "Deskband host for wbf" instead of adding the toolbar on my taskbar.

## How To Reproduce
No clue on how to reproduce it.

## Version
1.2.1 (Running on Windows 11, using StartAllBack taskbar)

## Logs/Screenshots Attachment
https://cdn.discordapp.com/attachments/1015843400832004117/1098093082915917946/AudioBand.log (Sent through discord, since filesize is 39mb (the issue happens later in the log file))
![Screenshot_257](https://user-images.githubusercontent.com/88485609/232962119-ccbab857-6d3e-43fe-917d-b2d7f9e4b464.png)

**Comment by Jimmyhogs** [comment]
I deleted the settings json file on the appdata folder of audioband, then let it generate a new one and put my stuff in again and that worked :p

**Comment by svr333** [comment]
Thanks for the report, checking the log file it seems to be caused due to Spotify getting too many requests from us, I'll see what I can do to fix it!

**Comment by Jimmyhogs** [comment]
Yeah, that's what they said on the thread they created from the github
issues on the server as well.

**Comment by WouterVanGoey** [comment]
I followed these steps (deleting the settings.json file and running the repair routine with the installer msi) and the problem remains.

**Comment by TechSupport26** [comment]
Can you share the log file so we can have a look.

**Comment by WouterVanGoey** [comment]
2024-03-22 14:24:47.0132 | INFO | AudioBand | Starting AudioBand. Version: "v1.2.3", OS: Microsoft Windows NT 10.0.22631.0
2024-03-22 14:24:47.0296 | ERROR | AudioBand | System.InvalidOperationException: The configuration is invalid. Creating the instance for type IAppSettings failed. An item with the same key has already been added. ---> SimpleInjector.ActivationException: An item with the same key has already been added. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at AudioBand.Settings.AppSettings.CheckAndLoadProfiles(Settings settings, UserProfile[] profiles) in C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\AudioBand\Settings\AppSettings.cs:line 254
   at AudioBand.Settings.AppSettings..ctor(IPersistentSettings persistSettings, IMessageBus messageBus) in C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\AudioBand\Settings\AppSettings.cs:line 46
   at lambda_method(Closure )
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistration`1.CreateInstance(Func`1 instanceCreator)
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistration`1.CreateInstanceWithNullCheck()
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistration`1.GetInterceptedInstance()
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistration`1.BuildExpression()
   at SimpleInjector.InstanceProducer.BuildExpressionInternal()
   at SimpleInjector.Internals.LazyEx`1.get_Value()
   at SimpleInjector.InstanceProducer.BuildExpression()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.BuildExpression()
   at SimpleInjector.InstanceProducer.VerifyExpressionBuilding()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.VerifyExpressionBuilding()
   at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt(InstanceProducer[] producersToVerify)
   at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt()
   at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
   at SimpleInjector.Container.Verify(VerificationOption option)
   at AudioBand.Deskband.ConfigureDependencies() in C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\AudioBand\Deskband.cs:line 141---START OF EXCEPTION---
System.InvalidOperationException: The configuration is invalid. Creating the instance for type IAppSettings failed. An item with the same key has already been added. ---> SimpleInjector.ActivationException: An item with the same key has already been added. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at AudioBand.Settings.AppSettings.CheckAndLoadProfiles(Settings settings, UserProfile[] profiles) in C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\AudioBand\Settings\AppSettings.cs:line 254
   at AudioBand.Settings.AppSettings..ctor(IPersistentSettings persistSettings, IMessageBus messageBus) in C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\AudioBand\Settings\AppSettings.cs:line 46
   at lambda_method(Closure )
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistration`1.CreateInstance(Func`1 instanceCreator)
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistration`1.CreateInstanceWithNullCheck()
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistration`1.GetInterceptedInstance()
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistration`1.BuildExpression()
   at SimpleInjector.InstanceProducer.BuildExpressionInternal()
   at SimpleInjector.Internals.LazyEx`1.get_Value()
   at SimpleInjector.InstanceProducer.BuildExpression()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.BuildExpression()
   at SimpleInjector.InstanceProducer.VerifyExpressionBuilding()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.VerifyExpressionBuilding()
   at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt(InstanceProducer[] producersToVerify)
   at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt()
   at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
   at SimpleInjector.Container.Verify(VerificationOption option)
   at AudioBand.Deskband.ConfigureDependencies() in C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\AudioBand\Deskband.cs:line 141
---END OF EXCEPTION

**Comment by svr333** [comment]
I think this issue is because you have a duplicate profile, can you check your `%appdata%/AudioBand/Profiles` folder to see if there are any duplicates?
If not, each profile.json file has a Name property inside of it (you can open it with any text editor like notepad), and check if you find any duplicates there. If you don't have any custom profiles you can also just delete them all and they will be regenerated!
