### ISSUE TITLE
GPU memory leak when hovering over settings sidebar items

### ISSUE THREAD

**Issue by Cynosphere** [AudioBand/AudioBand#115]
## Description
GPU memory leak when hovering over settings sidebar items
(see issue history for older report before figuring out the true memory leak)

## How To Reproduce
1. Open settings
2. Hover over sidebar menu items
2. Observe Explorer's GPU memory usage via a tool like Process Hacker/System Informer 

## Version
 - Windows version: Windows 10 22H2 (19045.3324)
 - AudioBand Version: 1.2.1

## Logs/Screenshots Attachment
N/A

**Comment by Cynosphere** [comment]
> Just a general question but have you observed any memory leaks if AudioBand is not running?

If you mean not enabled, I have no idea because I just keep the toolbar active 24/7 and just let idle mode do its thing.

> If this is an AudioBand issue then maybe the log file will be useful.

From when I driver crashed, which then caused Explorer to crash, resetting all toolbars:
```
2023-08-21 16:01:42.5952 | ERROR | AudioBand | Unhandled Exception---START OF EXCEPTION---
System.Runtime.InteropServices.COMException (0x88980406): UCEERR_RENDERTHREADFAILURE (Exception from HRESULT: 0x88980406)
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
---END OF EXCEPTION
```

**Comment by Cynosphere** [comment]
Album art does seem to be a contributor, turning it off and then switching songs a few times ends up not increasing VRAM compared to with it on.

**Comment by TechSupport26** [comment]
What I mean by not enabled is by removing AudioBand from the toolbar.

**Comment by Cynosphere** [comment]
> What I mean by not enabled is by removing AudioBand from the toolbar.

No VRAM is freed by disabling it.

Also opening the settings menu jumped VRAM to over a gig randomly.

**Comment by TechSupport26** [comment]
Okay. So this is definitely an AudioBand problem.
Can you try reinstalling AudioBand.

Also this is about as far as I can go but if you have questions I will do my best to answer.

@svr333 Any ideas?

**Comment by Cynosphere** [comment]
The settings menu memory increase happens anytime I hover over any sidebar option it seems

**Comment by Cynosphere** [comment]
Updated the OP to reflect this discovery of the true culprit.

Album art can still *technically* cause a memory leak, it would just take way longer than how fast you can cause it to leak from the settings menu.

**Comment by svr333** [comment]
Thanks for taking the time to report the issue!
GPU memory leaks are more likely to be a cause due to .net framework than anything because we never directly interact with the GPU (afaik at least), though it could very well be that we misuse some feature of .net framework and that that leads to gpu leaks.

Now I'm pretty noob when it comes to this, so I wouldn't know where to start debugging this or even replicating.
(I had Task Manager open when opening the settings menu and hovering over sidebar options with no spike in memory usage, but I assume thats not proper testing)

Would you mind helping me with testing this / sending a video of it happening or a memory usage graph or whatever?

**Comment by Cynosphere** [comment]
It seems to be happening when there is another application using the GPU like a game, so it might be with the compositing of the acrylic on the sidebar. But it also only happens if the application has been running for a while as well.

**Comment by Cynosphere** [comment]
I'm more incline to blame Java and AMD's drivers more than anything at this point considering I've now had instances where other applications like Firefox have ended up taking up all the VRAM.

**Comment by svr333** [comment]
All right, Hope you get your issue fixed!
