### ISSUE TITLE
Artwork not appearing

### ISSUE THREAD

**Issue by AshleyCheema** [AudioBand/AudioBand#118]
## Description
The artwork on Audio Source Spotify has stopped appearing. I've tried reauthenticating, created a new Spotify app and tried that and updated to the latest version. This did happen last week but ended up just working again...

## How To Reproduce
I have no idea how to reproduce the issue.

## Version
 - Windows version: Windows 10 Pro, Version - 22H2, OS build - 19045.3448

 - AudioBand Version [v 1.2.2]

## Logs/Screenshots Attachment
To obtain the log file, run `Windows-Key` + `R` and type in `%temp%`. Press enter.
Now look for the file called `audioband.log`.  

```
2023-09-20 10:20:36.9304 | ERROR | AudioSource(Spotify) | System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAudioSource.SpotifyAudioSource.<GetAlbumArtAsync>d__125.MoveNext() in C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\SpotifyAudioSource\SpotifyAudioSource.cs:line 805---START OF EXCEPTION---
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAudioSource.SpotifyAudioSource.<GetAlbumArtAsync>d__125.MoveNext() in C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\SpotifyAudioSource\SpotifyAudioSource.cs:line 805
---END OF EXCEPTION
```
[AudioBand.log](https://github.com/AudioBand/AudioBand/files/12671433/AudioBand.log)

I'm assuming my issue lays here - _The request was aborted: Could not create SSL/TLS secure channel._

![image](https://github.com/AudioBand/AudioBand/assets/23215872/cea03d5a-768a-4be1-ba11-e47069b847c9)

**Comment by JenniferVdL** [comment]
I have the same issue, since the new update i have no more artwork :(

**Comment by AshleyCheema** [comment]
As this happened before I updated to the latest version, I'm going to assume maybe Spotify changed something that's messed with it

**Comment by svr333** [comment]
Yeah I just went to check if it was on our end, but it broke on any version of AudioBand.
I'll keep this thread up to date once I figure out if Spotify or our Spotify Api Wrapper library is at fault!

**Comment by svr333** [comment]
Spotify still gives the correct image url, however when I try to download the image I get this error:
`The request was aborted: Could not create SSL/TLS secure channel`.

Which makes me assume there is an issue with Spotify's SSL certificate.
I'll see if it's bypassable in any way

**Comment by svr333** [comment]
I created a brand new application with just the functionality of AlbumArt and it worked out of the box, which was weird to say the least. (both were running .netframework4.8 and all dependencies were on the same versions)

After some digging I added this SecurityProtocol to the code and it works again.
How or why it suddenly broke overnight, no clue, but glad it's fixed I guess.
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 |
                                        SecurityProtocolType.Tls12 | SecurityProtocolType.Ssl3;`
                                        
I'll post a new release tonight, I'll try to resolve #117 first

**Comment by RivenSkaye** [comment]
Huh, maybe C# defaults to a protocol Spotify actively refuses for the transfer of assets?
I guess it'd be worth poking around on their forums to see if they made any changes; I can imagine them elevating minimal TLS version for example, with C# still defaulting to whatever ancient version MS likes

**Comment by svr333** [comment]
I have no idea, the weirdest part is that it broke overnight so something must've changed at Spotify.
Also weird is that on a brand new app with same settings it does work. but yea

**Comment by RivenSkaye** [comment]
> Also weird is that on a brand new app with same settings it does work. but yea

Maybe changed defaults on the C# internals end too? Might be worth rebuilding the old version with a newer toolchain to see if that solves the problem
