### ISSUE TITLE
If Audio Source is iTunes without iTunes being installed causes crash

### ISSUE THREAD

**Issue by S0und** [AudioBand/AudioBand#87]
## Description
If the user accidentally sets iTunes as an `Audio source` when iTunes is **not installed** the app crashes. The real issue starts when you try to change this back. Because you can't. When the app starts it's immediately want to access iTunes - which is still missing - so it crashes again. The user have no chance to pick a different `Audio source` before the app starts to use the currently set source. I had to manually edit the settings and change it to Spotify. This issue might not be unique to iTunes. 

## Expected behaviour
The app shouldn't hard crash if an `Audio source` is not installed. 

## How To Reproduce
1. Don't have iTunes installed
2. Change the Audio source to iTunes. 

## Version
 - AudioBand Version [e.g. 1.2.0]

## Logs/Screenshots Attachment
```
2022-09-12 14:33:06.1101 | DEBUG | AudioBand.UI.AudioBandToolbarViewModel | Activating new audio source "iTunes"
2022-09-12 14:33:06.1161 | ERROR | AudioSourceWrapper(iTunes) | Unhandled exception in wrapper---START OF EXCEPTION---
System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {DC0C2640-1415-4644-875C-6F4D769839BA} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at iTunesAudioSource.ITunesControls.Start() in C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\iTunesAudioSource\ITunesControls.cs:line 89
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
---END OF EXCEPTION

2022-09-12 14:33:06.1372 | ERROR | AudioBand | Unhandled Exception---START OF EXCEPTION---
System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {DC0C2640-1415-4644-875C-6F4D769839BA} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at iTunesAudioSource.ITunesControls.Start() in C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\iTunesAudioSource\ITunesControls.cs:line 89
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
---END OF EXCEPTION
```

**Comment by svr333** [comment]
Thanks for the report, will get this fixed - if you want to fix your install, you can manually go into `%appdata%/AudioBand` and either delete the `settings.json` (this will delete your settings) or open the file, find where it says `CurrentAudioSource: "iTunes"` and change it to 1CurrentAudioSource: ""`

**Comment by TechSupport26** [comment]
I appear to still have this issue in v1.2.1

https://user-images.githubusercontent.com/65631811/191628396-dee4c72c-8976-41bb-b610-b4a7925305fb.mp4


2022-09-22 09:25:21.6568 | DEBUG | AudioBand.UI.AudioBandToolbarViewModel | Activating new audio source "iTunes"
2022-09-22 09:25:21.6648 | ERROR | AudioSourceWrapper(iTunes) | Unhandled exception in wrapper---START OF EXCEPTION---
System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {DC0C2640-1415-4644-875C-6F4D769839BA} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at iTunesAudioSource.ITunesControls.Start() in C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\iTunesAudioSource\ITunesControls.cs:line 89
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
---END OF EXCEPTION

**Comment by svr333** [comment]
I probably overlooked something then, whoops
